### ISSUE TITLE
프로젝트 주제 선정

### ISSUE THREAD

**Issue by sms1875** [sms1875/industry-academic-project#1]

**Comment by sms1875** [comment]
주제 추천시스템인데 5분정도해서 간단히 생각해볼까요

**Comment by sms1875** [comment]
주제 추천시스템인데  5분정도해서 간단히 생각해볼까요

**Comment by sms1875** [comment]
주제 추천시스템인데 간단히 생각해볼까요

**Comment by bank2014** [comment]
게임 추천시스템 다들 어떠신가요

**Comment by bank2014** [comment]
https://github.com/persona7548/SteamRecommender_R

**Comment by bank2014** [comment]
스케일링? 기반 스팀 게임 추천 알고리즘이라네요

**Comment by sms1875** [comment]
넷플릭스처럼 자신이 본 영화들 별점 등으로 추천해주는것처럼 스팀게임 별점보고 어울리는 게임 추천해주는거 맞을까요

**Comment by bank2014** [comment]
네 그런거 같아요

**Comment by sms1875** [comment]
제가 스팀겜을 잘안해봐서 스팀은 게임추천해주는거 따로없나요?

**Comment by bank2014** [comment]
있긴 있어요

**Comment by ckmgkc** [comment]
저도 그 부분이 좀 고민이 되더라구요

**Comment by sms1875** [comment]
스팀에만 있으면 구지 스팀겜 추천아니라 다른게임 합쳐서 만드는걸로하면 될거에요

**Comment by ckmgkc** [comment]
스팀게임의 경우엔 게임 목록이 리스트로 쭉 나오고 그에 대한 정보가 있는 스팀 제공 게임이 아닌경우에는 리스트화를 어떻게 할지가 관건이네요 게임 정보같은것도 딱 기준이 없어서 문제가 될거같구요

**Comment by sms1875** [comment]
혹시 게임말고 다른 주제도 있나요

**Comment by sms1875** [comment]
저는 주식종목 추천 프로그램 같은거 떠오르네요

**Comment by bank2014** [comment]
제가 주식을 잘 몰라서 구현할 때 뭘 해야할지 막막할거 같네요

**Comment by bank2014** [comment]
모바일 게임 추천도 좋을거 같아요

**Comment by bank2014** [comment]
https://scienceon.kisti.re.kr/commons/util/originalView.do?cn=CFKO201629368424471&oCn=NPAP12621982&dbt=CFKO&journal=NPRO00376921

**Comment by sms1875** [comment]
추천생각나서 주식추천 적은거라 구현은 알아봐야될거같아요

**Comment by sms1875** [comment]
모바일게임은 아까 스팀게임이랑 별개로 하는거죠 같이 하는거 아니라?

**Comment by bank2014** [comment]
네

**Comment by ckmgkc** [comment]
만약 게임 추천 시스템으로 하게 된다면 플랫폼(pc 나 모바일 콘솔 등등이 있는데)  하나만 정해서 하나만 제대로 만드는게 좋겠죠?

**Comment by bank2014** [comment]
네 만약 한다면 구글 플레이 스토어 기준으로 하는게 쉬울거 같아요

**Comment by sms1875** [comment]
https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=JAKO201810866004192&dbt=NART

**Comment by sms1875** [comment]
관련 논문은 많은거같아서 참고할건 많으니까 우선 게임 추천할 범위부터 정확히 할까요

**Comment by sms1875** [comment]
스팀만/온라인 게임/구글 플레이스토어만

**Comment by bank2014** [comment]
온라인 게임이면 한국게임 말씀하시는 건가요?

**Comment by sms1875** [comment]
롤 같은 따로 서비스되는 게임들 생각햇어요

**Comment by sms1875** [comment]
혹시 스팀 게임추천에 평균 플탐같은거도 나오나요?

**Comment by bank2014** [comment]
그건 안 나와요

**Comment by ckmgkc** [comment]
개개인 플레이타임은 나오는데 게임 자체로 보면 따로 나오진 않아요

**Comment by ckmgkc** [comment]
스팀게임 추천기능과 비슷하게 하면서 스팀 세일과 연동해서 가격까지도 같이 생각해서 가성비 게임을 추천해주는건 어떨까요?

**Comment by sms1875** [comment]
평균 플탐 검색하면 통계내주는 사이트 있어서 스팀 게임추천에다가 플탐도 넣어서 오래 즐길수있거나 가성비같은거 내면 어떨까요

**Comment by sms1875** [comment]
맞죠

**Comment by sms1875** [comment]
정리해보면 스팀추천에서 가격대비 플탐으로 가성비 요소도 넣어서 추천해주는걸로 하면될까요

**Comment by sms1875** [comment]
스팀할인하면 가격이 싸지니까 가성비도 높아지고

**Comment by bank2014** [comment]
근데 어떻게 세일하는걸 알아낼 수 있는지 감이 안 오네요

**Comment by bank2014** [comment]
스팀 api에 그런 기능이 있을까요

**Comment by ckmgkc** [comment]
세일 주기가 어느정도 정해져있고 이벤트가 추석 설날 여름 겨울 등 있어서 세일 기록이 나오는 사이트가 따로 있는데 그걸 참고하면 되지 않을까 싶네요

**Comment by sms1875** [comment]
아마 크롤링할때 가격 정보도 나오지 않을까싶은데

**Comment by bank2014** [comment]
메이플 로아 이런 온라인 rpg 게임 시세를 얻어와서 사는게 좋을지 파는게 좋을지 추천해주는 시스템은 어떤가요

**Comment by sms1875** [comment]
평균 시세 얻어와서 매니아같은데 평균시세보다 싸게 올라오면 사는게 좋다고 추천해주는거 맞나요?

**Comment by bank2014** [comment]
예를들어  재료1 재료2 합치면  아이템 1 이 나올때  재료1의 가격이 특정 게임머니 이하일때  거래소에서 구매후 아이템 1을 제작해서 팔면 이익을 얻는 구조를 만들고 그 특정 이하 가격으로 내려가면 알림(추천) 해주는 식으로

**Comment by sms1875** [comment]
이게 한 게임 추천해주는게 아니라 게임 전체적으로 하는건가요?

**Comment by bank2014** [comment]
많으면 많을 수록 좋을거 같아요

**Comment by sms1875** [comment]
제가 검은사막 게임하는데 검은사막 거래소 연동해서 비슷한 기능 구현한 사이트가 있는데

**Comment by sms1875** [comment]
거기도 게임거래소 연동이랑 레시피들 따로 추가해야하는데 게임 한개아니라 여러개면 힘들지 않을까요

**Comment by bank2014** [comment]
각자 하는 게임을 만들면 되지 않을까요 ? 전 로아합니다

**Comment by sms1875** [comment]
로아 거래소 홈페이지에서 확인되면 아마 추출될건데

**Comment by bank2014** [comment]
확인돼요

**Comment by sms1875** [comment]
거래소에 재료 a b가격이랑 조합c 가격 비교하고 아이템 매물 확인해서 매물 없을때 기대 차익값 같은거 계산하는거 맞을까요

**Comment by bank2014** [comment]
네
재료1  2현재 시세가 각각 30G 이고 제작 비용이 10G 일 때  재료12로 만들 수 있는 아이템1 의 가격이 70G 이상일 때  지금 만들면 얼마나 이익을 보는지 알림(추천)해주는 시스템이에요
게임 재화가 여러가지니까
 그 재화들의 실제 가격도 알려주고요 파는게 이득일 때 알림(추천) 해주는 거 어떤가요

**Comment by sms1875** [comment]
그럼 주제 경매장이랑 스팀추천 이렇게 생각해보면될까요

**Comment by sms1875** [comment]
또 다른주제있을까요

**Comment by sms1875** [comment]
발표자료는 주말에 만들어도되니까 금요일까지 주제 정하는걸로할까요 생각나는거있으면 추가해보면서

**Comment by bank2014** [comment]
마지막 하나는 코인이나 주식 추천이 좋을 것같아요
차별성은 UI를 토스 처럼 깔끔하고 심플하게 해서 주식 잘 모르는 사람도 쓸 수 있게 어플? 로 만들면 좋을거 같아요

**Comment by sms1875** [comment]
주식이나 코인한다면 거래량 재무 그런거 싹 긁어와서 하는거랑 간단히 뉴스 공시 키워드추출하기 두개정도로 나뉠거같아요

**Comment by sms1875** [comment]
거래량 재무 그런거 긁어서 하는건 기본증권앱에서 이미있어서 별효과 없을거같고 간단히 공시뉴스 뜨는거로 추천하면 아마 스캘핑용으로 쓸수는 있을거에요

**Comment by sms1875** [comment]
근데 로아도 a+b=c 하는 템들이 많나요?

**Comment by sms1875** [comment]
그럼 저희가 웹서버 따로 만들어서 거기서 거래소 차익 계산하는 방식으로 하는건가요

**Comment by bank2014** [comment]
네

**Comment by sms1875** [comment]
전 그것도 괜찮을거같네요 배너 광고달아서 수익 창출하는식으로 하면

**Comment by sms1875** [comment]
우선 나온 거래소랑 스팀게임중에 거래소로 한다면 까페에 글 올려서 교수님의견 들어보는게 좋을거같아요

**Comment by bank2014** [comment]
어떤식으로 여쭈어 보는게 좋을까요

**Comment by bank2014** [comment]
제가 글 올릴게요

**Comment by sms1875** [comment]
지금 아니라 금요일쯤에 정하구 올리면될거같은데 그냥 위에나온거 정리해서 주제선정으로 괜찮은가 확인받으면될거같아요

**Comment by bank2014** [comment]
아하 알겠습니다

**Comment by bank2014** [comment]
아 방금 확인 해보니까 원래 거래소계산기 로아온에 있엇는데 개인인증 해야 확인되게 바뀌고 사라졌다네요
그럼 아마 구현은 힘들 것같아요 ㅜㅜ

**Comment by sms1875** [comment]
네 그럼 내일까지 혹시 다른 아이디어 있으면 내보고 없으면 스팀추천으로 하죠

**Comment by bank2014** [comment]
넵

**Comment by bytecell** [comment]
Prof: Cafe에서도 언급했던 것처럼, 각자가 개발에서 맡은 부분을 진행하다가 맞딱뜨리는 어려움들을 각각 issue 로 파서 기록해도 됩니다. 참고하세요.
