### ISSUE TITLE
직무발명신고 및 권리승계합의서

### ISSUE THREAD

**Issue by ckmgkc** [sms1875/industry-academic-project#10]

**Comment by ckmgkc** [comment]
지분은 어떻게 나눌까요? 저는 그냥 똑같이 나눠도 좋을거같은데

**Comment by sms1875** [comment]
저도 33하면될거같아요

**Comment by ckmgkc** [comment]
[직무발명신고 및 권리승계합의서.zip](https://github.com/sms1875/industry-academic-project/files/7656105/default.zip)

**Comment by ckmgkc** [comment]
제꺼 작성해서 올렸습니다. 혹시 퍼센트에이지 변경하고 싶으시면 변경하셔도 되요.

**Comment by sms1875** [comment]
[직무발명신고 및 권리승계합의서(정보추가 후, 서명을 넣어서 HWP확장자 파일로 제출).zip](https://github.com/sms1875/industry-academic-project/files/7656130/HWP.zip)

**Comment by bank2014** [comment]
[직무발명신고 및 권리승계합의서(정보추가 후, 서명을 넣어서 HWP확장자 파일로 제출).zip](https://github.com/sms1875/industry-academic-project/files/7656183/HWP.zip)
