### ISSUE TITLE
개발 현황 

### ISSUE THREAD

**Issue by bank2014** [sms1875/industry-academic-project#11]
nginx랑 flask 연동했습니다

**Comment by bank2014** [comment]
지금 어떤 부분 개발하고 계신지 말씀 해주세요

**Comment by sms1875** [comment]
api 가져와서 구상중이에요

**Comment by sms1875** [comment]
https://weejw.tistory.com/555 4번 유저 정보  이용해야되서

**Comment by sms1875** [comment]
서버에서 키 받아주셔야되요

**Comment by bank2014** [comment]
DB 연동하려 하면 자꾸 에러가 나는데 몇 시간째 해결이 안되네요
