### ISSUE TITLE
발표 회의

### ISSUE THREAD

**Issue by bank2014** [sms1875/industry-academic-project#2]

**Comment by sms1875** [comment]
안녕하세요

**Comment by sms1875** [comment]
먼저 1.problom 부터 정할게요

**Comment by sms1875** [comment]
카톡에 올린 사진 예로 보시면되고
게임추천 input 사용자의 게임평점, 태그 output 게임 추천 순위

**Comment by sms1875** [comment]
혹시 추가하거나 바꿀꺼있을까요 다듬거나

**Comment by bank2014** [comment]
Input에 평균 플탐  가격

**Comment by sms1875** [comment]
가격은 저희가 받아오는거라 input에 넣는건 아니에요

**Comment by bank2014** [comment]
메타/오픈 크리틱 점수

**Comment by ckmgkc** [comment]
문제점 : 코로나 시대에 집에서 즐길거리인 게임을 찾는 사람들이 많아지면서 게임을 잘 모르는 사람들까지도 게임에 대해 알아보게 되었지만 어떤 게임이 있는지,  또 그것이 자신에게 맞는 게임인지 잘 모르는 경우가 많다. 

이정도는 어떨까요

**Comment by sms1875** [comment]
문제점은 제가 생각해보니까 이미 스팀에 게임추천 기능이 많이 있는데 플레이타임대비 가격인 가성비에 대한 자료가 부족해서 그걸 게임추천 기능에 추가하였다고 차별성으로 가는게 좋을거같아요

**Comment by bank2014** [comment]
차별성은 뭐가 있을까요

**Comment by sms1875** [comment]
저희 차별성이 게임플레이타임대비 가격을 받아와서 가성비를 넣는거죠

**Comment by sms1875** [comment]
이건 지금 스팀 검색기능에 없는거니까요

**Comment by bank2014** [comment]
이거 실용성도 평가 한다고 했나요?

**Comment by sms1875** [comment]
실용성보단 기존 기술대비 차별성으로 평가하실걸요

**Comment by sms1875** [comment]
그리고 찾아보니까 할인 기록들 모아둔 사이트도 있어서 거기서 게임 할인 기록도 추출해서

**Comment by sms1875** [comment]
평소 할인 자주하는 게임인지 아닌지도 알아낼수 있을거같아요

**Comment by ckmgkc** [comment]
실용성도 평가에 들어갈거같던데요 아마... 결국 이걸 사람들이 쓸건지에 대해서 말씀하시기도 했던거같아요

**Comment by sms1875** [comment]
네 가성비를 추가하는거면 충분히 실용성 있을거같아요 전

**Comment by sms1875** [comment]
가격 낮은순하면 500원짜리 이상한게임들 나오는거라 단순 가격비교가 아니라 플레이타임대비 가격이니까요

**Comment by bank2014** [comment]
가성비보다 정확한 평가 기준으로 추천해주는 시스템은 어떤가요

**Comment by ckmgkc** [comment]
게임 추천 마지막에 지금살건지 할인을 대비하는게 좋을지 대략 다음 세일에 할인될 가격과 남은 날짜등을 알려주면 게임 구매에 좀 더 도움이 되는 방향으로 차별성을 갖을 수 있을거같아요

**Comment by sms1875** [comment]
네 저도 그렇게 할인기록으로 예측하는게 좋을거같아요

**Comment by ckmgkc** [comment]
정확한 기준...은 어떤게 좋을까요

**Comment by sms1875** [comment]
저희가 정확한 평가기준으로 추천하는거면 스팀 인터랙티브 추천시스템보다 정확해야 개선점이있는데

**Comment by sms1875** [comment]
그건 힘들거같아서 가성비나 할인으로 차별점을 두려고했어요

**Comment by bank2014** [comment]
그 가끔 게임 중에

**Comment by bank2014** [comment]
평론가 점수는 높은데 유저 점수는 낮거나  호불호 갈리는 게임인데 스팀 평가는 압도적으로긍정적인 게임들 있잖아요

**Comment by sms1875** [comment]
그런 게임들이 보통 플레이타임이 높을수록 인기가 많은게임이니까

**Comment by sms1875** [comment]
그런점도 추출할수있을거라봐요

**Comment by bank2014** [comment]
진짜 여론 점수 넣어서 추천해주는 거에요  그러니까 차별성에  가성비+ 진짜 평점 이렇게 두개로

**Comment by sms1875** [comment]
진짜 평점이 어떤거에요?

**Comment by bank2014** [comment]
여론 점수요

**Comment by sms1875** [comment]
스팀점수에 메타크리틱 점수까지 넣는거 맞나요?

**Comment by sms1875** [comment]
구체적인 여론점수가 어떤게 있을까요

**Comment by bank2014** [comment]
아뇨  스팀 댓글에 긍정적 부정적 댓글 비율로 점수 주면 될 거같아요

**Comment by bank2014** [comment]
그리고 댓글 중에 장점 단점 쓴거 따로 추출해서 사용자한태 보여주게

**Comment by bank2014** [comment]
예를 들어 위처3 가 지금 스팀 평점이 압도적으로긍정적이라  단점이 안 보이는데 막상 하면 졸리다는 사람이 많거든요

**Comment by ckmgkc** [comment]
저는 사실 점수는 잘 믿지 않는편인데 100시간 플레이 똥겜이예요 같은걸 많이 보고 30분 플레이 재밌었어요도 봤어서 플레이 타임이 길면 결국 그 게임에 흥미를 갖고 즐겼다고 생각해서 플탐이 진짜라고 생각해요 점수 좋다고해서 플레이 했는데 그닥이였던것도 있던거같구요

**Comment by bank2014** [comment]
게임 추천에  장점: ~~ 단점: 졸림   이렇게 뜨게끔 해서 차별성을 두는거죠

**Comment by sms1875** [comment]
긍정적댓글 부정적댓글 하나씩 따서 보여주는건 괜찮은거같아요

**Comment by sms1875** [comment]
그 압도적 긍정적 이런건 이미 추천시스템에 옆에 나와있네요

**Comment by bank2014** [comment]
네 사람들이 그거만 보고 게임 사서 후회하니까 이런 세세한 부분까지 저희가 구현을 해서 추천을 해주는거\죠

**Comment by bank2014** [comment]
여기에 가성비까지 채점해서 추천해주면 차별성은 확실할 거 같아요

**Comment by sms1875** [comment]
장점 단점으로 명확히 하기보단
긍정적댓글 부정적댓글 해서 보여주면 될거같네요

**Comment by bank2014** [comment]
네

**Comment by ckmgkc** [comment]
댓글의 추천수를 기준으로 2~3개씩 대표로 뽑아서 보여주면 좋을거같네요

**Comment by bank2014** [comment]
문제점은 아까 나왔듯이  사람들이 평점 점수를 신뢰하지 않는다라고 정하면 좋아보여요

**Comment by sms1875** [comment]
문제점:스팀 게임 추천 기능은 이미 존재하지만 그 게임의 가격이나 플레이타임에 대한 정보가 부족해 비싼 값을 주고도 짧은 시간밖에 즐기지 못할 수 있다. 이를 개선하려고 가격과 전세계유저의 평균 플레이타임을 받아와 가성비를 계산해 추천시스템에 포함시키고 게임의 할인기록들과 긍정적,부정적 댓글들을 받아와 게임을 선택하는데 도움을 주고자 한다

**Comment by bank2014** [comment]
저도 안 믿거든요 메타크리틱이나 그런거

**Comment by sms1875** [comment]
수정할거나 덧붙일것들 써주세요

**Comment by bank2014** [comment]
+기존 게임 평점에 신뢰성이 떨어지는 것을 보완한다

**Comment by ckmgkc** [comment]
좋은거같아요 이거 근데 교수님이 피드백을 주시나요?

**Comment by sms1875** [comment]
게임을 선택하는데 도움을 주고 기존 게임 평점의 신뢰성이 떨어지는 것을 보완한다

**Comment by sms1875** [comment]
음 주시지 않을까요?

**Comment by sms1875** [comment]
그럼 INPUT OUTPUT 정하면

**Comment by sms1875** [comment]
output은 게임 추천 순위가 될거고 input이

**Comment by ckmgkc** [comment]
자신의 스팀 계정 혹은 즐겼던 게임 목록, 플레이 스타일에 대한 몇가지 질문-답변 이런걸 받으면 좋지 않을까요

**Comment by sms1875** [comment]
자신 스팀id하면 보유 게임들 추출할수 있을거같은데

**Comment by sms1875** [comment]
네 저도 스팀계정으로 하는게 좋을거같아요

**Comment by bank2014** [comment]
문제점: 스팀 게임 추천 기능은 이미 존재하지만 게임의 가격이나 플레이타임에 대한 정보가 부족해 비싼 값을 주고도 짧은 시간밖에 즐기지 못할 수 있다. 또한 메타크리틱 등 대중적인 게임 평점을 사람들이 신뢰하지 않는 추세이기에 이에 대한 해결책이 필요해보인다.  이를 개선하기 위해 가격과 전세계유저의 평균 플레이타임을 받아와 가성비를 계산해 추천시스템에 포함시킨다. 또한 긍정적,부정적인 댓글의 비율과 그 댓글들을 받아와 게이머들이 한 줄의 평가 점수에만 의존해 게임을 구매하고 후회하는 불상사를 막는다.

**Comment by bank2014** [comment]
이대로 수정해주세요

**Comment by sms1875** [comment]
네

**Comment by bank2014** [comment]
.

**Comment by sms1875** [comment]
input : 스팀 계정 ->계정내 나의 게임과 플레이타임
output : 추천 게임 순위

**Comment by sms1875** [comment]
이런식으로 할까요?

**Comment by bank2014** [comment]
네

**Comment by ckmgkc** [comment]
알고리즘은 스팀게임 전체 목록에서 input 데이터를 바탕으로 사용자와 비슷한 유저층을 골라서 그 유저들이 즐겼던 게임들을 추리고 플레이 타임을 데이터화 시켜서 저장, 그렇게 플레이타임 기반 추천 게임이 몇개 나오면 그것들을 할인 기록 사이트에서 데이터를 가져와서 최근 할인 가격과 할인률 할인 주기까지 포함해서 보여줄 수 있도록 하고 마지막에 스팀 홈페이지의 대표댓글 추천-비추천 3개씩 볼 수 있도록 가져오는식 이면 어떨까요

**Comment by sms1875** [comment]
그럼 2.해결방법

**Comment by sms1875** [comment]
1.스팀게임 전체 목록에서 input 데이터를 바탕으로 사용자와 비슷한 유저층을 골라서 그 유저들이 즐겼던 게임들을 추리고 
2.플레이 타임을 데이터화 시켜서 저장, 그렇게 플레이타임 기반 추천 게임이 몇개 나오면 
3.그것들을 할인 기록 사이트에서 데이터를 가져와서 최근 할인 가격과 할인률 할인 주기까지 포함해서 보여줄 수 있도록 하고 
4.마지막에 스팀 홈페이지의 대표댓글 추천-비추천 3개씩 볼 수 있도록 가져오는식 이면 어떨까요

**Comment by bank2014** [comment]
좋네요

**Comment by sms1875** [comment]
게임 플레이타임도 기록사이트에서 가져오는게 편하고 전세계라 정확할거에요

**Comment by sms1875** [comment]
1번은 그럼 기존 게임추천 결과를 긁어올까요 저희가 직접 만들까요?

**Comment by sms1875** [comment]
전 구지 저희가 만들필요는 없다생각하는데

**Comment by bank2014** [comment]
둘다 하죠

**Comment by ckmgkc** [comment]
저는 좋은거같아요 이걸 순서도나 알고리즘 표현 방식으로 나타내서 보여줄지는 선택하셔서 발표하시면 좋을거같아요

**Comment by bank2014** [comment]
아 잘 못 봤네요   그냥 기존 추천 결과를 긁어오는게 좋아보여요

**Comment by ckmgkc** [comment]
저는 일단 시작은 스팀 긁이 맞는거같고 저희가 서비스를 오래 하게 된다면 그 데이터로 결과물을 얻어서 따로 우리 추천픽 같은 탭을 추가하게되는것도 좋아보여요  지금 당장에 저희가 판단해서 추천하는건 신뢰성이 떨어지는거같네요

**Comment by sms1875** [comment]
그럼 1.기존 스팀 추천 데이터 결과 획득
2. 추천 데이터에 가격과 플레이타임을 추가해 재정렬
3. 할인 기록사이터에서 게임들의 할인 기록과 주기를 추출해 보여줌
4. 스팀의 긍정적,부정적 댓글 3개씩 출력해 플레이어의 의견 확인

**Comment by ckmgkc** [comment]
나중에 추후 이런기능까지 개발되면 좋을거같다는 식으로 언급해주면 좋지않을까요

**Comment by sms1875** [comment]
이런식으로 정리하면 될까요

**Comment by ckmgkc** [comment]
네 일단 지금까지 나온걸 바탕으로하면 이정도면 좋을거같아요

**Comment by sms1875** [comment]
혹시 스팀 인터랙티브 캡처좀 가능한가요 전 짤려서 안보이네요 게임이

**Comment by sms1875** [comment]
차별성은 기존 게임추천 시스템은 없던 플레이타임을 고려한 가성비와 할인에 대한 정보를 추가해 소비 금액에 대한 만족성을 높일 수 있다.

**Comment by sms1875** [comment]
이런식으로 하면될까요

**Comment by ckmgkc** [comment]
네 그거랑 한눈에 정리해서 보여주는 편의성도 언급하면 좋을거같아요 할인같은건 스팀에선 지금 할인 아니면 안보여주고 기록도 안보여줘서

**Comment by sms1875** [comment]
차별성은 기존 게임추천 시스템은 없던 플레이타임을 고려한 가성비와 할인에 대한 정보를 추가해 소비 금액에 대한 만족성을 높일 수 있고 게임마다 따로 할인기록을 찾는 수고를 줄일 수 있다.

**Comment by sms1875** [comment]
제가 스팀 인터랙티브 저렇게 짤리는데 원래 저런건가요?

**Comment by bank2014** [comment]
저도 짤리네요

**Comment by sms1875** [comment]
결과 예시 올려봤는데
어떠신가요

**Comment by bank2014** [comment]
괜찮네요

**Comment by bank2014** [comment]
![KakaoTalk_20210912_141129144](https://user-images.githubusercontent.com/69072509/132973072-508a686c-6b4e-471b-bb61-e6a46052dda6.png)

**Comment by sms1875** [comment]
가성비는 숫자같은거로 하면 애매할테니까 저희가 기준정해서 나눠야할거에요

**Comment by sms1875** [comment]
시간당 천원 미만이면 최고 천원~만원이면 보통 이런식으로

**Comment by ckmgkc** [comment]
저는 숫자로 보여주는게 제일 와닿을거라 생각하는데 최고나 보통같은 등급으러 나누면 등급만 보여주나요?

**Comment by sms1875** [comment]
5000원 게임을 100시간 즐긴다면 20점이고
2만원 게임을 50시간 즐기면 2.5점 이런식인데 보기 힘들지않을까요

**Comment by sms1875** [comment]
2만원으로 50시간만 즐겨도 충분히 오래 즐기는 게임인데

**Comment by bank2014** [comment]
둘다 보여주는건 어떤가요

**Comment by bank2014** [comment]
어차피 점수로 환산하고 그걸 등급으로 나누는 거잖아요

**Comment by sms1875** [comment]
좋음/시간당 ~원 이런식으로 맞나요?

**Comment by sms1875** [comment]
그럼 괜찮을거같아요

**Comment by bank2014** [comment]
네

**Comment by sms1875** [comment]
![image](https://user-images.githubusercontent.com/67058185/132973233-77a432fa-477f-46f8-8251-aaf2d5c6f41b.png)

**Comment by sms1875** [comment]
이거 저희가 기존추천에 저거 값만 표시하는게 아니라 추천값 받아온다음 저 값을 넣고 다시 정렬하는거죠?

**Comment by bank2014** [comment]
네

**Comment by sms1875** [comment]
[발표자료.pptx](https://github.com/sms1875/industry-academic-project/files/7149037/default.pptx)

**Comment by sms1875** [comment]
자료 간단하게 만들었는데 어떠신가요

**Comment by bank2014** [comment]
고생하셨습니다  이슈는 오늘 밤에 닫을게요

**Comment by bank2014** [comment]
잘 만드셨네요

**Comment by sms1875** [comment]
혹시 디자인만 간단히 해주실분 있나요 플로우차트 같은건 제가 만들수있는데

**Comment by sms1875** [comment]
꾸미기는 잘못해서

**Comment by ckmgkc** [comment]
ppt 꾸미는거 말씀이신가요?

**Comment by sms1875** [comment]
네

**Comment by ckmgkc** [comment]
저도 템플릿 아무거나 받아서 대충 적용하는 정도인데 괜찮을까요

**Comment by sms1875** [comment]
네 괜찮아요

**Comment by sms1875** [comment]
[1주차발표.pptx](https://github.com/sms1875/industry-academic-project/files/7149077/1.pptx)

**Comment by ckmgkc** [comment]
[2 주차 프로젝트 발표.pptx](https://github.com/sms1875/industry-academic-project/files/7149123/2.pptx)

**Comment by sms1875** [comment]
[2주차 발표자료.pptx](https://github.com/sms1875/industry-academic-project/files/7149152/2.pptx)

**Comment by bank2014** [comment]
살펴봤는데 더 수정할 부분이 없네요 고생하셨습니다

**Comment by sms1875** [comment]
[2주차 발표자료.pptx](https://github.com/sms1875/industry-academic-project/files/7149166/2.pptx)

**Comment by sms1875** [comment]
조금 다듬었어요

**Comment by bytecell** [comment]
정영섭Prof: 스크롤 압박이 어마어마하네요 ^^

참고로, Close 했던 이슈도 나중에 필요 시에는 reopen 할 수 있습니다.
