### ISSUE TITLE
Steam api 정보 공유

### ISSUE THREAD

**Issue by bank2014** [sms1875/industry-academic-project#5]
.

**Comment by sms1875** [comment]
https://partner.steamgames.com/doc/store/getreviews 
스팀 댓글 api

**Comment by sms1875** [comment]
https://www.google.com/search?q=steam+api+recommendations&biw=1205&bih=1279&sxsrf=AOaemvJmYHhSL91Qxum5he6JiSQmkIatGg%3A1633079667741&ei=c9FWYYPfLIeJoATUj4_QBw&ved=0ahUKEwjD5PDr76jzAhWHBIgKHdTHA3oQ4dUDCA4&uact=5&oq=steam+api+recommendations&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECc6BwgAEEcQsAM6BAgjECc6BwgAEIAEEAo6CAgAEIAEELEDOgsIABCABBCxAxCDAToNCAAQgAQQhwIQsQMQFDoFCAAQgAQ6BAgAEEM6BwgAELEDEEM6CggAEIAEEIcCEBRKBAhBGABQ1kNYnmFg9WNoAXACeACAAYUBiAHWCpIBBDAuMTKYAQCgAQKgAQHIAQnAAQE&sclient=gws-wiz
스팀 게임 추천 api들

**Comment by sms1875** [comment]
https://github.com/ckatzorke/howlongtobeat
게임 플레이타임 api

**Comment by sms1875** [comment]
https://github.com/smiley/steamapi
스팀 api

**Comment by sms1875** [comment]
https://github.com/woctezuma/steam-labs-recommender
인터랙티브 api같은데 이해가 안되서 알아봐야될거같네요

**Comment by sms1875** [comment]
![image](https://user-images.githubusercontent.com/67058185/135744999-ca669545-7c1b-4133-b057-bd16d203c609.png)
게임 플레이타임 api는 잘 동작하네요

**Comment by sms1875** [comment]
인터랙티브 api는 작동은하는데 개인 계정 쿠키 필요해서 쓸수있는진 잘 모르겠네요

**Comment by sms1875** [comment]
[요구사항정의서.zip](https://github.com/sms1875/industry-academic-project/files/7273437/default.zip)

**Comment by bank2014** [comment]
그러면 어떻게 할까요

**Comment by sms1875** [comment]
https://partner.steamgames.com/doc/webapi_overview/oauth
