### ISSUE TITLE
성능 평가

### ISSUE THREAD

**Issue by sms1875** [sms1875/industry-academic-project#6]

**Comment by ckmgkc** [comment]
지난번에 교수님께도 말씀드렸지만 추천 게임중에서 사용자가 더보기 버튼을 누른 횟수, 결과적으로 마음에 들었던 게임이 없었다면 없다는 버튼을 만들어서 만족도를 평가하는건 어떨까요

**Comment by ckmgkc** [comment]
문제는 평가를 받은걸 어떻게 반영하고 개선할지가 애매하네요

**Comment by sms1875** [comment]
처음에 목록에 원하는게임이 없으면 원하는 게임이 없다고 피드백을 받고
저희가 추천한 게임을 나중에 만족했는지 별점으로 피드백받는거 맞나요?

**Comment by bank2014** [comment]
리스트에 맘에 든 게임이 없어서 더보기 누르는 상황인가요

**Comment by sms1875** [comment]
이해했습니다

**Comment by sms1875** [comment]
저는 좋은거같아요

**Comment by ckmgkc** [comment]
그리고 정확도를 높인다고 생각한다면 처음에 사용자 정보 수집할 때 자기가 중요하게 생각하는게 뭔지 고르는 부분도 있으면 추천 정확도를 올릴 수 있지 않을까요?

**Comment by sms1875** [comment]
![image](https://user-images.githubusercontent.com/67058185/136797867-41a31d71-9321-44a4-97fd-eecec41c1d84.png)

**Comment by sms1875** [comment]
더보기를 많이 누르고 추천받은 게임 결과 평점이 안좋으면

**Comment by ckmgkc** [comment]
사용자입장에서 같은 내용에서 순서만 바뀐 추천내용을 비교해서 설문을 하면 왜 설문하는지 모르겠다고 생각할 수 있을거같아서 스팀꺼랑 비교한다기보단 별점으로 만족도 조사가 좀 더 낫지 안을까 싶어요 전

**Comment by sms1875** [comment]
네

**Comment by ckmgkc** [comment]
내일 발표는 누가하나요?

**Comment by ckmgkc** [comment]
더보기 카운팅은 살리는건가요? 그거 말고는 서비스 후  설문이 된거같은데

**Comment by bank2014** [comment]
그니까 더보기한 이유를 설문으로 받아서 성능평가한다는 것이죠?

**Comment by sms1875** [comment]
네 다 살려서 하죠 이게 유저경험으로 저희가 받는거니까

**Comment by sms1875** [comment]
더보기한 이유는 목록 맘에 안들어서일꺼니까 그냥 횟수만 카운트하면되고
게임 선택햇으면 그 게임에 대한 평점이랑 이유를 따로 받아요

**Comment by ckmgkc** [comment]
네 명석님 말씀이 맞아요 제가 생각한거로는

**Comment by ckmgkc** [comment]
추가할 내용은 더 없을거같습니다

**Comment by bank2014** [comment]
근데 결국엔 추천리스트가 마음에 안 들어서 설문하는건데 2번을 넣을 이유가 굳이 있을까요

**Comment by sms1875** [comment]
그럼 2번은 빼죠

**Comment by bank2014** [comment]
[배급사] 클릭하면  배급사가 싫어서 그런걸로 해석하면 되죠

**Comment by ckmgkc** [comment]
키워드도 넣고 키워드를 안골라도 자유의견란을 만들어서 제출하도록 하면 둘다 해결할 수 있지 않을까 싶네요

**Comment by sms1875** [comment]
그럼이제 ppt랑 발표 어떻게 할까요

**Comment by ckmgkc** [comment]
한명이 하는게 좋을거같아요 내용이 그렇게 많지는 않으니까

**Comment by ckmgkc** [comment]
제가 만들어서 걸리시는거같아서 제가 만들었는데... ㅠ 너무 많이 하셨는데 일단 이번까진 하시고 다음 발표는 빼고 저희 둘이 돌릴까요

**Comment by bank2014** [comment]
ppt 그럼 대충 개요는 어떻게하면 좋을까요
