### ISSUE TITLE
review 코멘트 토론

### ISSUE THREAD

**Issue by bank2014** [sms1875/industry-academic-project#8]
.

**Comment by bank2014** [comment]
오현소프트 리뷰 작성부터 먼저할까요

**Comment by bank2014** [comment]
[오현소프트_Mid-term PPT.pptx](https://github.com/sms1875/industry-academic-project/files/7613396/_Mid-term.PPT.pptx)

**Comment by sms1875** [comment]
[REVIEW.docx](https://github.com/sms1875/industry-academic-project/files/7613416/REVIEW.docx)

**Comment by bank2014** [comment]
일단 problem에서 1번 대답 생각하신 거 있으시면 적어주세요

**Comment by sms1875** [comment]
1번은 적합도가 우선이고 거기에서 가격은 평점이나 상품구매후기처럼 참고하는 자료로 쓰는거라고 하면 될거같아요

**Comment by bank2014** [comment]
여기서 적합도라는게 뭔지 이해가 안 가는데 이게 뭘까요

**Comment by ckmgkc** [comment]
기타 부분에서 신규게임에 대한 왜곡된 결과보단 홍보가 더 효과있다고 말씀주셨었는데 물론 new 라는 태그를 붙임으로써 홍보효과는 제공하고 있고 다만 서비스 초기다 보니 여러가지 개선되지 않은 버그가 있을 수 있고 플레이 타임이 짧은 유저들이 가볍게 적어놓은 리뷰들이 많을 수 있으니 주의해달라는 표시를 했습니다. 정도로 답변하면 좋을거같습니다

**Comment by bank2014** [comment]
적합도 안에 가격(가성비)가 포함된거 아닌가요?

**Comment by sms1875** [comment]
해당 이용자가 재미있게 플레이 할 만한 게임이 있는데 그것의 가격이 부담스러울 수도 있다고 생각합니다. 이 경우 적합도와 가격 중 어느 것에

**Comment by sms1875** [comment]
그러니까 적합도가 재미있게 플레이 할 만한 게임들이겟죠?

**Comment by bank2014** [comment]
아

**Comment by ckmgkc** [comment]
적합도라고 말하는게 아무래도 게임 가격이랑은 상관없이 그냥 사용자에게 맞고 재밌는 게임이라는거 같은데 예로 들면 저는 마크 재밌어보이고 하고 싶은데  그돈주고 할만큼은 안끌려서 안하거든요 이런 느낌 아닐까요?

**Comment by sms1875** [comment]
네 저도 그런거같네요

**Comment by ckmgkc** [comment]
저는 굳이 따지면 가성비쪽이 더 먼저라고 생각해요 물론 저희가 계산하는 가성비가 완벽하게 모든 정보를 커버하는 것은 아니지만 앞으로 쌓여갈 데이터를 바탕으로 개선할 점이고, 가성비가 충족되지 않으면 아무리 게임이 재밌어보여도 결국 구매는 하지 않는 선에서 그칠것이라고 생각합니다.

**Comment by ckmgkc** [comment]
요새 게임이 유튜브 에디션이다 트위치 에디션이다 하면서 하고 싶지만 비싼 게임들 대리만족하는 경우가 많다보니 일단 가성비가 먼저라고 생각합니다. 비싸면 안산다고 생각해요.

**Comment by sms1875** [comment]
이게 저희가 주제 좀 바꿔서 가성비 기준으로 추천하는게 아니라 추천하고 가성비 등 정보를 한눈에 추가로 확인시키는 거잖아요?

**Comment by sms1875** [comment]
이걸 가성비 위주로 하면 추천할때 부터 개인 맞춤 추천이 아니라 가성비 위주로 추천한다는건가요?

**Comment by bank2014** [comment]
그러면 답변을
"게임의 가격을 비중있게 고려하는 게이머들이 저희의 주 타켓층이므로 가격은 적합도보다 우선시 됩니다. 이 유저층은 아무리 재미있는 게임이라도 가격이 너무 비싸다면 구매하지 않기 때문입니다."
이렇게 쓰면 될까요

**Comment by bank2014** [comment]
가성비 위주로 추천해야겠죠 가성비가 우선이면

**Comment by sms1875** [comment]
네

**Comment by ckmgkc** [comment]
개인 맞춤 게임들 리스트가 이미 있으니 그 리스트 안에서는 가성비를 위주로 정렬하는게 맞다고 생각해요 적합도라는게 정확도 뽑기가 어렵고 무엇을 기준으로 적합도라는 시스템을 도입할 수 있을지에 대해서 다시 생각해봐야하기 때문에 저희가 하던거면 가성비 위주라는 답변이 맞는거같습니다. 적합도를 아예 고려 하지 않는 것은 아니지만 우선순위는 그렇게 보는게 맞는거같아요.

**Comment by sms1875** [comment]
그럼 위에 답변이 맞는거같아요

**Comment by bank2014** [comment]
그럼 다음 2번 답변 작성해보죠

**Comment by sms1875** [comment]
스팀 추천시스템은 게임 이용 내역에서 플레임 타임등도 고려해서 분석하는걸로 알고 있습니다
하지만 유저가 조금만 게임을 즐기고 얼마나 만족한지 만족도까지 따로 확인하는 작업은 어려울 것 같습니다

**Comment by bank2014** [comment]
이건 1. 어쩔 수 없다  2. 특정 플레이시간 미만인 게임은 걸러서 보겠다   이렇게 나뉠 수 있겠네요 다른 의견 있으신가요

**Comment by sms1875** [comment]
추천 시스템을 만든걸 이용하는거라 어쩔수 없다고 하는게 좋을거같아요

**Comment by ckmgkc** [comment]
2번의 경우 일단 문제점에 어느정도 동의한다고 생각해요. 짧은 플레이 타임을 인터렉티브 게임 추천 서비스에서 어떻게 처리하고 있는지 모르겠지만, 일단 제 생각에는 그 게임도 관심이 있으니까 구매를 했던거고 막상 내용물이 재미없었으니 조금 해보다 그만 둔 게임이 되었을텐데, 일단 장르나 그 게임의 여러가지 속성등이 어느 정도 맞았으니 구매를 했었기 때문에 그 게임이 실질적인 내용물과는 관계없이 새로운 게임 추천에 의미있는 영향을 주지 않나 생각합니다.

**Comment by bank2014** [comment]
네 그럼 위에 답변 그대로 적을게요

**Comment by ckmgkc** [comment]
맞는 말이긴 해서  현재 프로젝트의 내용상 개선하기 힘든 부분이고 추후에 개선이 된다면 좋을 부분쯤에 넣어두는것도 좋은거 같습니다. 다만 이걸 개선하려면 애초에 인터렉티브 게임 추천 리스트를 받아오는게 아닌 저희가 추천 알고리즘을 만들어서 기존 서비스보다 더 나은 서비스를 제공할만큼의 퀄리티를 갖춰야 하니까 사실상 힘들지 않을까 싶어요.

**Comment by sms1875** [comment]
그럼 나중에 개선할 점으로 넣어두면 좋겟네요

**Comment by bank2014** [comment]
그럼 제가 정리해서 적어볼게요 잠시만요

**Comment by sms1875** [comment]
현 시스템은 스팀 추천 알고리즘을 이용하는거인데 라이브러리의 게임 이용 시간까지 분석합니다 하지만 이 게임 이용시간으로 만족도까지 알아내기는 현재는 어려울 것 같습니다. 후에 저희가 추천 시스템을 개선할때 게임의 만족도까지 반영하여 만들면 좋을 것 같습니다

**Comment by ckmgkc** [comment]
3번 같은 경우엔 
단 하나의 게임을 추천하는 것이 아닌 리스트업을 다시 해서 보여주는 것이므로 사용자에게 여러가지 선택지가 주어집니다. 따라서 가성비 위주의 리스트업이 되어있으므로 상위게임부터 보게 되면 가성비 기준이겠지만, 결국 가성비가 맞아도 게임의 마음에 들지 않는 부분이 있으면 점점 아래로 내려가면서 자신이 더 끌리는 게임을 찾게 되겠죠. 따라서 가성비만으로 모든 것을 판단해서 추천해주는 것이 아닌, 가성비를 중점으로 한눈에 다른 정보까지 파악할 수 있도록 도와주는 서비스이기 때문에 많은 다수의 이용자들에게도 적합하게 서비스해줄 수 있을 것이라 생각합니다.  

한마디로 가성비가 중요하지만 전부는 아니라는 얘기죠.

**Comment by sms1875** [comment]
5번은
 왜곡된 결과가 새로 출시된 게임은 유저들의 평균 플레이타임 데이터가 제대로 쌓이지 않아 가성비를 나타낼 때 왜곡되어 나타난다는 뜻이였습니다. 이런 게임들을 그냥 표시하면 가성비가 안좋게 나타날수 있기 때문에 신규게임 태그 등을 따로 표시한다는 뜻이였습니다

**Comment by bank2014** [comment]
답변: 저희도 그 문제점에 대해 어느정도 동의합니다. 하지만 인터렉티브 게임 추천 시스템에서 짧은 플레이 타임까지 고려하고 있는지는 모르겠으나, 저희 생각에는 그 게임도 장르나 그 게임이 가진 여러가지 요소 등이 유저와 어느 정도 맞았으니 구매를 했었을 거라 추정합니다. 따라서 해당 게임의 내용과 상관없이 그 게임이 추천된 것은 충분히 의미있지 않나 추청합니다. 그래도 이 부분은 향후 시간적 여유가 충분하다면 플레이 타임이 짧은 게임은 필터링을 하는 식으로 개선해 보겠습니다.

**Comment by bank2014** [comment]
2번 답변 이렇게 적을게요

**Comment by sms1875** [comment]
네

**Comment by ckmgkc** [comment]
evaluation 의 경우 반박하기 좋은 예시가 배그 옵치 인데 그 게임을 사서 할만큼의 가성비를 느꼈기 때문에 구매했다는 반증이 되겠죠. 무료 게임의 경우엔 가성비를 따질 수 없는게 에초에 구매 비용이 들지 않기 때문에 판매용 게임과 비교되는 것이 옳지 않다고 봅니다. 

추가적으로 예시로 들어주신 두 게임 다 할인이라는 기간에 집중적으로 구매를 많이 하는 경향도 있는 것으로 보아 할인으로 인한 가성비 상승 또한 구매 결정에 도움을 준다고 생각할 수 있을거 같습니다.

**Comment by ckmgkc** [comment]
근데 혹시 생필품에 가성비를 따지나요? 필요하면 사는게 생필품 아닌지

**Comment by bank2014** [comment]
생필품이 한두개가 아니면 가성비를 따져서 하나만 사겠죠

**Comment by ckmgkc** [comment]
핵심은 꼭 사야하는건 아니기 때문에 안사면 그만인 게임한테도 가성비가 중요한가? 라는 질문이겠네요

**Comment by sms1875** [comment]
지금 나온거 종합해볼가요우선

**Comment by sms1875** [comment]
"게임의 가격을 비중있게 고려하는 게이머들이 저희의 주 타켓층이므로 가격은 적합도보다 우선시 됩니다. 이 유저층은 아무리 재미있는 게임이라도 가격이 너무 비싸다면 구매하지 않기 때문입니다."

답변: 저희도 그 문제점에 대해 어느정도 동의합니다. 하지만 인터렉티브 게임 추천 시스템에서 짧은 플레이 타임까지 고려하고 있는지는 모르겠으나, 저희 생각에는 그 게임도 장르나 그 게임이 가진 여러가지 요소 등이 유저와 어느 정도 맞았으니 구매를 했었을 거라 추정합니다. 따라서 해당 게임의 내용과 상관없이 그 게임이 추천된 것은 충분히 의미있지 않나 추청합니다. 그래도 이 부분은 향후 시간적 여유가 충분하다면 플레이 타임이 짧은 게임은 필터링을 하는 식으로 개선해 보겠습니다.

단 하나의 게임을 추천하는 것이 아닌 리스트업을 다시 해서 보여주는 것이므로 사용자에게 여러가지 선택지가 주어집니다. 따라서 가성비 위주의 리스트업이 되어있으므로 상위게임부터 보게 되면 가성비 기준이겠지만, 결국 가성비가 맞아도 게임의 마음에 들지 않는 부분이 있으면 점점 아래로 내려가면서 자신이 더 끌리는 게임을 찾게 되겠죠. 따라서 가성비만으로 모든 것을 판단해서 추천해주는 것이 아닌, 가성비를 중점으로 한눈에 다른 정보까지 파악할 수 있도록 도와주는 서비스이기 때문에 많은 다수의 이용자들에게도 적합하게 서비스해줄 수 있을 것이라 생각합니다.

evaluation 의 경우 반박하기 좋은 예시가 배그 옵치 인데 그 게임을 사서 할만큼의 가성비를 느꼈기 때문에 구매했다는 반증이 되겠죠. 무료 게임의 경우엔 가성비를 따질 수 없는게 에초에 구매 비용이 들지 않기 때문에 판매용 게임과 비교되는 것이 옳지 않다고 봅니다. 추가적으로 예시로 들어주신 두 게임 다 할인이라는 기간에 집중적으로 구매를 많이 하는 경향도 있는 것으로 보아 할인으로 인한 가성비 상승 또한 구매 결정에 도움을 준다고 생각할 수 있을거 같습니다.

왜곡된 결과가 새로 출시된 게임은 유저들의 평균 플레이타임 데이터가 제대로 쌓이지 않아 가성비를 나타낼 때 왜곡되어 나타난다는 뜻이였습니다. 이런 게임들을 그냥 표시하면 가성비가 안좋게 나타날수 있기 때문에 신규게임 태그 등을 따로 표시한다는 뜻이였습니다

**Comment by bank2014** [comment]
3번 가성비가 주관적인 요소라고 하는 리뷰는 좀 이상한데요 리뷰 자체가

**Comment by sms1875** [comment]
가성비 중요도 체감 말하는거 아닐까요

**Comment by bank2014** [comment]
네 근데 수치를 어떻게 해석하냐에 따라서 해결될 사항인데 이걸 이해를 못하고 지적하는거 같은데요

**Comment by sms1875** [comment]
가성비는 플레이타임/가격으로 나눈 값으로 저희가 기준을 나누어 표시합니다 그리고 사용자마다 가성비의 중요도 체감이 다르다는 뜻이면 단 하나의 게임을 추천하는 것이 아닌 리스트업을 다시 해서 보여주는 것이므로 사용자에게 여러가지 선택지가 주어집니다. 따라서 가성비 위주의 리스트업이 되어있으므로 상위게임부터 보게 되면 가성비 기준이겠지만, 결국 가성비가 맞아도 게임의 마음에 들지 않는 부분이 있으면 점점 아래로 내려가면서 자신이 더 끌리는 게임을 찾게 되겠죠. 따라서 가성비만으로 모든 것을 판단해서 추천해주는 것이 아닌, 가성비를 중점으로 한눈에 다른 정보까지 파악할 수 있도록 도와주는 서비스이기 때문에 많은 다수의 이용자들에게도 적합하게 서비스해줄 수 있을 것이라 생각합니다.

**Comment by sms1875** [comment]
[둘리_reviewResponse.docx](https://github.com/sms1875/industry-academic-project/files/7613487/_reviewResponse.docx)

**Comment by sms1875** [comment]
수정할거 있을까요

**Comment by bank2014** [comment]
□차별성
(1) 가성비라는 항목을 추가한다고 하셨습니다. 그런데 이 ‘가성비’는 해당 게임을 플레이하는 이용자마다 천차만별이라고 생각합니다. 애매모호한 척도인 이 가성비가 많은 이용자들을 대상으로 서비스하는 이 프로젝트에 적합한지 의문입니다.

답변:  가성비 지수는 단순히 플레이 타임을 가격으로 나눈 값입니다. 여기에는 저희의 주관적인 요소가 들어가 있지 않고 애매모호한 부분도 없습니다. 이건 개개인이 저희의 가성비 지수를 해석하기 나름입니다.  가성비가 제일 좋은 순서로 리스트업이 되어있으므로 본인이 생각하기에 가성비를 덜 중요시 여긴다면 아래로 내리면됩니다.

**Comment by bank2014** [comment]
이렇게 수정 어떨까요

**Comment by sms1875** [comment]
너무 공격적인데 제가 바꿔볼게요

**Comment by bank2014** [comment]
"가성비 지수는 해석하기 나름이다" 이 것만 넣어서 수정해주세요

**Comment by sms1875** [comment]
가성비 지수는 단순히 플레이 타임을 가격으로 나눈 값입니다. 만약 가성비를 받아들이는 점이 사용자마다 다르다고 하신거면 사용자가 이용할 때 추천리스트가 가성비 순으로 정렬되어 있으므로 리스트를 확인하면서 가성비가 상대적으로 낮아도 마음에 드는 게임을 찾을 수 있습니다

**Comment by sms1875** [comment]
더 없으면 발표할사람 정하고 발표자료 만들까요

**Comment by ckmgkc** [comment]
1번) 

저희 서비스가 가성비를 위주로 추천 리스트업을 해주지만 말씀해주신 적합성 부분에서도 고려하여 리스트를 구성합니다. 이 중 우선순위를 두자면 저희는 가성비 부분을 우선순위로 두고 있는데, 유저가 생각하기에 게임이 아무리 재밌어보여도 그에 맞는 가격이 아니라면 할인을 기다리거나 트위치, 유튜브 에디션 등의 대리만족으로 끝내는 경우가 많습니다. 따라서 어느정도 사용자에게 맞는 게임들 중에서 구매가능성이 높은 순서대로 리스트업 하는 것을 목표로 하고 있기 때문에 가성비에 우선순위를 둔다고 말씀드릴 수 있을 것 같습니다.

**Comment by sms1875** [comment]
네

**Comment by sms1875** [comment]
발표자료 발표자가 만드는걸로할까요

**Comment by bank2014** [comment]
네

**Comment by ckmgkc** [comment]
넵 내용 별다른거 없이 만드는데 얼마 안걸릴거같아서 괜찮을거같아요

**Comment by sms1875** [comment]
사다리 만들게요

**Comment by sms1875** [comment]
만드셧네

**Comment by ckmgkc** [comment]
[둘리조-왕십리곱창볶음조 피어리뷰.pptx](https://github.com/sms1875/industry-academic-project/files/7613565/-.pptx)

**Comment by ckmgkc** [comment]
ppt 작성해서 올렸습니다. 확인해보시고 수정하실 부분 있으면 말씀주세요.

**Comment by sms1875** [comment]
저는 좋은거 같아요
