### ISSUE TITLE
발명설명서

### ISSUE THREAD

**Issue by sms1875** [sms1875/industry-academic-project#9]

**Comment by ckmgkc** [comment]
저희가 주장할 수 있는 권리 부분이 있을까요? 사실 짜깁기 서비스 정도라고 생각해서 특별하게 주장할 만한 권리가 없어보이네요 ㅠ

**Comment by sms1875** [comment]
발명 배경 : 기존 스팀에서 제공하던 추천 시스템에 정보가 부족하여 별도로 게임에 대한 정보를 검색해 찾아야 해서 불편함을 느꼈습니다

**Comment by bank2014** [comment]
가성비 기준 추천

**Comment by bank2014** [comment]
이걸 권리로 쓸까요?

**Comment by sms1875** [comment]
그럼 가성비로 나눠서 하는거 기준을 지금

**Comment by sms1875** [comment]
구체적으로 정해둘까요

**Comment by bank2014** [comment]
네

**Comment by ckmgkc** [comment]
가성비로 나눠서 하는거 가 정확히 뭐죠?

**Comment by sms1875** [comment]
추천 시스템에서 가성비를 어떻게 나타낼지

**Comment by sms1875** [comment]
표시기준 정하면 될거같아요

**Comment by sms1875** [comment]
국문 : 종합 게임추천 서비스
영문 : comprehensive game recommendation service

**Comment by ckmgkc** [comment]
해당 게임의 장르 게임들을 가성비 순으로 나열한 다음에 상위 30% 좋음 40% 중간 30% 나쁨 으로 표기하는건 어떨까요

**Comment by sms1875** [comment]
1.장르별로 top100 게임의 게임 평균 플레이타임을 구한다
2.추천 게임의 플레이타임과 장르별 평균 플레이타임을 비교한다

**Comment by sms1875** [comment]
이게 비교하는게 평균 플레이타임이 30시간이고 치면 나누는걸 어떻게 나눠야될까요

**Comment by ckmgkc** [comment]
치면 나눈다가 어떤 말씀이시죠? 일단 가성비라서 가격이 들어가야하니까 플탐가지고만 비교하면 안될거같아요

**Comment by sms1875** [comment]
아그러네요

**Comment by sms1875** [comment]
top 100 에서 무료인 게임 제외하고 플레이타임/가격 평균을 구해서 만원당 10시간이라고 나오면

**Comment by ckmgkc** [comment]
아니면 장르별 기준을 정하고 그 이상과 미만으로 따지는 법이 있는데 기준점 잡기가 너무 애매해서... 줄세우는게 낫지 않나 싶어요

**Comment by sms1875** [comment]
만원당7시간 아래면 나쁨 13시간 이상이면 좋음 인가요?

**Comment by ckmgkc** [comment]
가성비 결과값이 시간당 얼마 로 나오는게 좀 더 보기 좋지 않을까요? 그리고 아예 top 10 을 기준으로 정해보는건 어떨까요 최상위권 게임이 기준이 되는거로 비교하면 근거있는 기준점이 될거같아요

**Comment by sms1875** [comment]
[발명설명서.zip](https://github.com/sms1875/industry-academic-project/files/7655957/default.zip)

**Comment by sms1875** [comment]
좋음 보통 나쁨이 아니라 그냥 시간당얼마로 바로 나타내는건가요?

**Comment by sms1875** [comment]
가성비 기준으로 높은순정렬하는거고

**Comment by ckmgkc** [comment]
좋음 보통 나쁨이 맞아요 기준을 정하는데 그냥 모든 게임중 평균 내면 신뢰성이 떨어질거같아서요 평균값에서 위아래로 얼마나 차이를 둘지도 문제인데 생각보다 어렵네요

**Comment by ckmgkc** [comment]
근데 제가 생각하는건 일단 시간당 얼마인지는 값으로 나와야하고 딱 눈에 보이는건 좋음 보통 나쁨이고 커서를 올리면 데이터값으로 가성비값이 보였으면 좋겠어요 아니면 점수로 보여주는건데... 점수보단 실제 계산한 값이 나오는게 좋아보여요

**Comment by sms1875** [comment]
마우스 대면 시간당 얼마 나오는거죠?

**Comment by sms1875** [comment]
이거 5번으로 6번하는거니까 저희가 추천시스템으로 커뮤니티 한다는거 쓰면 될거같긴해요

**Comment by sms1875** [comment]
5번은 그냥 짜집기한 내용 다 써볼까요

**Comment by ckmgkc** [comment]
권리로 쓸 수 있을거같진 않고 가성비 부분을 좀 구체화시켜서 가성비 측정 기준을 권리로 써보는게 좋을거같아요 짜깁기는 다른 사이트 데이터 기반으로 하는거라 권리주장이 쉽지 않을거같아요

**Comment by bank2014** [comment]
저도 저희만의 가성비 측정 알고리즘?을 권리로 쓰는게 좋아보여요

**Comment by sms1875** [comment]
그럼 가성비 부분 기준 정리좀 해볼까요

**Comment by ckmgkc** [comment]
가성비 기준 측정
해당 장르의 판매 순위 top10 을 기준으로 하여 게임의 가격 / 플레이 타임 으로 가성비를 수치화 한 다음 이것의 평균을 기준으로 하여 이것의 1.3배 이상을 가성비 좋음, 0.7배 이하를 나쁨, 그 중간을 보통으로 표기함.

여기에 살을 붙여볼까요

**Comment by sms1875** [comment]
[발명설명서 (2).zip](https://github.com/sms1875/industry-academic-project/files/7656016/2.zip)

**Comment by ckmgkc** [comment]
[발명설명서.zip](https://github.com/sms1875/industry-academic-project/files/7656034/default.zip)

**Comment by ckmgkc** [comment]
조금 수정하고 덧붙였습니다.

**Comment by sms1875** [comment]
http://kportal.kipris.or.kr/kportal/search/total_search.do

**Comment by sms1875** [comment]
http://kportal.kipris.or.kr/kportal/search/total_search.do

**Comment by sms1875** [comment]
7번 참고자료로 쓸까요?

**Comment by sms1875** [comment]
[발명설명서.zip](https://github.com/sms1875/industry-academic-project/files/7656071/default.zip)

**Comment by sms1875** [comment]
더 수정할거 없나요?

**Comment by ckmgkc** [comment]
네 저도 가성비 랑 게임 추천 같은거 검색해서 보고있었는데 가성비 광고 추천도 넣으면 좋을거같구요 안넣어도 되요

**Comment by sms1875** [comment]
선우씨도 수정할거 없나요?

**Comment by bank2014** [comment]
제가 조금 수정해서 다시 올릴게요

**Comment by bank2014** [comment]
[발명설명서.zip](https://github.com/sms1875/industry-academic-project/files/7656122/default.zip)
